#!/bin/sh -ex

### Not documented as such, but inhibits annoying crash dumps.
export ERL_CRASH_DUMP=""

ERL=`which erl`
if ! test -n "ERL"; then
    display_error "Error: erl is required. Add it to 'PATH'"
    exit 1
fi

$ERL -pa $(pwd)/ebin -boot start_sasl -noshell \
    -eval 'c:c(salt_test).' \
    -eval 'salt_test:all().' \
    -eval 'init:stop().'
